load:
	deno run --location=http://localhost ./loader.ts

run:
	deno run --allow-net --location=http://localhost ./main.ts

run-watch:
	deno run --allow-net --location=http://localhost --watch ./main.ts

run-dev:
	deno run --allow-net --location=http://localhost --watch ./dev.ts
